### ISSUE TITLE
Is this software open source?

### ISSUE THREAD

**Issue by dawidcha** [pingostack/nginx-websocket-module#1]
Hi,

I'm keen to start using and potentially contributing to this software, but would like to know under what terms it would be licensed. I think you had used https://opensource.org/licenses/BSD-3-Clause in pingOS - would this be licensed under the same terms? - and if so, can you copy the LICENSE file from pingOS to ngx-websocket_module?

**Comment by im-pingo** [comment]
> Hi,
> 
> I'm keen to start using and potentially contributing to this software, but would like to know under what terms it would be licensed. I think you had used https://opensource.org/licenses/BSD-3-Clause in pingOS - would this be licensed under the same terms? - and if so, can you copy the LICENSE file from pingOS to ngx-websocket_module?

Good 👍🏻
